name: Matrix Demo
on: push
jobs:
  build:
    runs-on: ${{ matrix['operating-system'] }}
    strategy:
      matrix:
        node-version: [18, 20, 22]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix['node-version'] }}
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
`